@startuml
skinparam monochrome true
skinparam nodesep 20
skinparam ranksep 40
left to right direction

["WebApp"] --> ["React"]
["React"] --> ["DOM"]
["DOM"] --> ["Utils"]
["React"] --> ["JSX"]
["JSX"] --> ["Parser"]
["Parser"] --> ["Utils"]
["WebApp"] --> ["Router"]
["Router"] --> ["History"]
["History"] --> ["PathParser"]
["PathParser"] --> ["Utils"]
["Router"] --> ["PathParser"]
["WebApp"] --> ["StateManager"]
["StateManager"] --> ["Events"]
["StateManager"] --> ["Storage"]
@enduml